### ISSUE TITLE
Javascript displayed in HTML output frame when editing HTML

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/learn#159] opened 2018-06-07 09:54 UTC
@camachado commented on [Thu Jun 07 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17476)

#### Describe your problem and - if possible - how to reproduce it
While editing HTML in the code edit frame, Javascript is displayed in the HTML output frame

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10 Pro

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/2438129/41074672-2d3d3148-69d7-11e8-8bbe-f4eaa976114a.png)

**Comment by nikrb** [comment] 2018-06-07 11:42
@raisedadead is this a duplicate of #66 ?

**Comment by Bouncey** [comment] 2018-06-15 10:38
Closing as duplicate, thanks @camachado for reporting and @nikrb for keeping us sane.

**Closed by Bouncey** 2018-06-15 10:38 UTC
Labels: bug, critical path, help wanted
